### ISSUE TITLE
Update Q line to include new Second Ave. stops

### ISSUE THREAD

**Issue by ssmirti** [nydailynews/restaurant-guide#13]
We'll need to rearrange the Q line to be in line with the current changes, which now include stops along second ave at 72st, 86th st, and 96th st. The stops currently on the interactive map for the Q after 57th st and onward into Queens should be switched to the W line.

**Comment by freejoe76** [comment]
Related to #12

**Comment by freejoe76** [comment]
This is done.

**Comment by ssmirti** [comment]
I'm not seeing this on the map. Does it take a while to update?
