### ISSUE TITLE
Figure out why certain restaurants aren't appearing

### ISSUE THREAD

**Issue by freejoe76** [nydailynews/restaurant-guide#18]
per @ssmirti

This is one:
>some of the stories on the N line aren't pulling into the map, I'm not sure why because the abstracts are correct
http://www.nydailynews.com/life-style/eats/times-square-takeout-food-doesn-terrible-article-1.2717320

**Comment by freejoe76** [comment]
We figured it out: The article wasn't tagged with the "eating along the N line" tag in the CMS.

**Comment by ssmirti** [comment]
This might be an issue with other lines. I'll double check to make sure every article is tagged correctly.
