### ISSUE TITLE
Add W line, and W line geometry.

### ISSUE THREAD

**Issue by freejoe76** [nydailynews/restaurant-guide#19]

**Comment by ssmirti** [comment]
Joe can we make this addition before launch?

**Comment by ssmirti** [comment]
Just thinking about this more, I just think it's weird to not have the W line visible on the nav bar. We have every other subway line but this one.

**Comment by freejoe76** [comment]
Okay, I'll re-add. We're not as close to the finish line as we had thought.

**Comment by ssmirti** [comment]
ok cool.

**Comment by freejoe76** [comment]
THIS IS DONE

**Comment by freejoe76** [comment]
whoops forgot about the stop labels

**Comment by freejoe76** [comment]
This is done.
