### ISSUE TITLE
Remove S line from nav

### ISSUE THREAD

**Issue by ssmirti** [nydailynews/restaurant-guide#20]
We don't need to include the S line since there a few different options and it's not that highly used.

**Comment by freejoe76** [comment]
Done, also, added documentation on how to do this https://github.com/nydailynews/restaurant-guide#how-to-remove-a-subway-route

**Comment by ssmirti** [comment]
Joe will this also be removed from the splash page?

**Comment by freejoe76** [comment]
@ssmirti Good catch. That's fixed and the documentation updated.

**Comment by ssmirti** [comment]
ok nice. Thanks.
