### ISSUE TITLE
Build an iframe include to go in the review articles that makes it easy to get back to the map

### ISSUE THREAD

**Issue by freejoe76** [nydailynews/restaurant-guide#28]
1. Most review articles are written about a particular line. The first thing the iframe should do is make it easy to get back to that line.
2. We don't want to maintain different html file for each line, so the iframe should be easily configurable (`include.html#a` for the a-line, or something like that) for each line.
3. The include will go at the bottom of each article and should work on both desktop (~600px wide) and handheld (320px minimum)

**Comment by freejoe76** [comment]
Should it maybe just be a javascript include instead?

**Comment by freejoe76** [comment]
Update on in-article module design

![01_subwayfare_defaultmodule](https://cloud.githubusercontent.com/assets/125554/25593540/05676590-2e8b-11e7-97ef-d98333cd8848.jpg)
![02_subwayfare_returnmodule](https://cloud.githubusercontent.com/assets/125554/25593541/07c180be-2e8b-11e7-94b4-95b80b7ccbbb.jpg)

**Comment by kelliparker** [comment]
I'm done futzing around with this and it's been deployed to QA. Anything else?

**Comment by freejoe76** [comment]
Great! I'm going to close this.
