### ISSUE TITLE
additional content A line content  appearing at end of line

### ISSUE THREAD

**Issue by ssmirti** [nydailynews/restaurant-guide#29]
The Hoyt - Schermerhorn stop has content on both the A line and G line. When on the A line page, the G line Hoyt - Schermerhorn content displays at the end of the line.

![image](https://cloud.githubusercontent.com/assets/25779035/23760955/428c601a-04bf-11e7-9eff-e72a67bbe96b.png)

**Comment by freejoe76** [comment]
This is fixed, and I bet @ssmirti fixed it.

**Comment by ssmirti** [comment]
Yup
