### ISSUE TITLE
Adjust layout / design of card to put text in one area

### ISSUE THREAD

**Issue by freejoe76** [nydailynews/restaurant-guide#42]
![06_subwayfare_firstcard](https://cloud.githubusercontent.com/assets/125554/24270842/25264a02-0fed-11e7-89cc-f77179dce87f.jpg)

**Comment by freejoe76** [comment]
Everything but the top, line-name card's finished. @leekristena, were we really going to kill the photo of the line?

**Comment by leekristena** [comment]
I'm OK with killing the photo of the line - I think I actually like the graphic a little better. But I was thinking we needed some more explanatory text there. Like "scroll/swipe to explore restaurants along the A line." Something like that. I thought the feedback we want indicated we should be a little more explicit about what the reader should do. What do you think?

**Comment by freejoe76** [comment]
That sounds good! I just wanted to make sure before I obliterate the photo.

**Comment by freejoe76** [comment]
This is done.
