### ISSUE TITLE
Create a separate page that indexes the restaurant reviews by borough

### ISSUE THREAD

**Issue by freejoe76** [nydailynews/restaurant-guide#58]
Put it in the splash page template

**Comment by freejoe76** [comment]
Organize it like this:

## Brooklyn
### MTA A train stops
* [High Street stop restaurants](http://www.nydailynews.com/life-style/eats/eating-line-brooklyn-heights-article-1.1986192)
* [Jay Street / Borough Hall restaurants](http://www.nydailynews.com/life-style/eats/eating-line-jay-st-metrotech-article-1.1980629)
* Stop Name restaurants with link etc.

### MTA 4 train stops
...

**Comment by ssmirti** [comment]
This is done.
