### ISSUE TITLE
We've got one article on the A line that spans three stops: Rockaway Blvd, 80th St and 88th St

### ISSUE THREAD

**Issue by freejoe76** [nydailynews/restaurant-guide#60]
http://www.nydailynews.com/life-style/baking-supplies-guyanese-meals-bengali-treats-ozone-park-article-1.1924357

I'm not sure how we address this. cc @ssmirti

**Comment by ssmirti** [comment]
I think I know how to fix this. I have to add an ampersand to connect the abstracts. That should work.

**Comment by freejoe76** [comment]
@ssmirti fixed it! Thanks Steve!
