### ISSUE TITLE
Figure out the URL we will be publishing this at.

### ISSUE THREAD

**Issue by freejoe76** [nydailynews/restaurant-guide#63]
Specifically, the directory names.

Candidates (add your ideas in the comments):

1. `/projects/nyc-subway-restaurant-guide/`
2. `/projects/nyc-subway-restaurant-reviews/`
3. `/projects/nyc-subway-map-restaurant-reviews/`

**Comment by ssmirti** [comment]
We should probably have the name of the project somewhere in the URL "subway fare"

**Comment by freejoe76** [comment]
DONE http://nydn.us/subwayfare
