### ISSUE TITLE
Create line specific social share images for title cards

### ISSUE THREAD

**Issue by ssmirti** [nydailynews/restaurant-guide#68]
when sharing a line from a title card, we want the image to brand the line that's being shared.

**Comment by kelliparker** [comment]
More info, please.

**Comment by ssmirti** [comment]
I don't think we need this anymore. This was before we decided to use the subway fare landing image as the social share. @freejoe76 agree?

**Comment by freejoe76** [comment]
@ssmirti Agreed. Though it would be fun,  and since fun is a core value here at NYDNi, perhaps we re-open this issue at a later date.
