### ISSUE TITLE
fix overlapping text on J line

### ISSUE THREAD

**Issue by ssmirti** [nydailynews/restaurant-guide#73]
![image](https://cloud.githubusercontent.com/assets/25779035/25594496/d78e989c-2e8e-11e7-8b1d-016a2ac456be.png)

**Comment by freejoe76** [comment]
@kelliparker to adjust the alignment of the stop labels on the J line, look here: https://github.com/nydailynews/subway-stop-restaurant-lookup-table/blob/master/js/app.js#L82

And don't forget your hosts file hack.

**Comment by ssmirti** [comment]
I think the fix to this made an issue with Canal St overlapping Essex St.

![image](https://cloud.githubusercontent.com/assets/25779035/25871793/a9a80e1a-34d6-11e7-9c41-ec9613fc8e8c.png)

**Comment by kelliparker** [comment]
I don't see the Essex issue. I see the issue at Broad Street

**Comment by ssmirti** [comment]
Oh yeah it's fixed now. Maybe cache had to clear for me or something.

**Comment by ssmirti** [comment]
But yeah I see that issue at Broad St. too

**Comment by kelliparker** [comment]
Fixed again
