### ISSUE TITLE
Title card text on handheld intermittently aligns itself in bad, bad ways

### ISSUE THREAD

**Issue by freejoe76** [nydailynews/restaurant-guide#74]

**Comment by ssmirti** [comment]
![image uploaded from ios](https://cloud.githubusercontent.com/assets/25779035/25752907/b1fd6d00-3187-11e7-9a51-413fb689f2a2.jpg)

**Comment by freejoe76** [comment]
WONTFIX WEDNESDAY CAME EARLY
