### ISSUE TITLE
Activate B line on the nav

### ISSUE THREAD

**Issue by ssmirti** [nydailynews/restaurant-guide#81]
We're starting to get content for the B line.

**Comment by freejoe76** [comment]
WELCOME BACK STEVE!

**Comment by ssmirti** [comment]
Will we activate this before launch?

**Comment by freejoe76** [comment]
@ssmirti Maybe!

**Comment by freejoe76** [comment]
@ssmirti update: Yes.

**Comment by freejoe76** [comment]
whoops forgot about the stop labels

**Comment by freejoe76** [comment]
This is done.
