### ISSUE TITLE
Sub nav on article flushed left

### ISSUE THREAD

**Issue by ssmirti** [nydailynews/restaurant-guide#87]
The sub nac on articles within the subway map appear flushed left and not center. 
![image uploaded from ios](https://user-images.githubusercontent.com/25779035/29375124-ebdbee8e-8281-11e7-8bc6-173c78a57152.jpg)

**Comment by freejoe76** [comment]
http://www.nydailynews.com/life-style/eats/find-italian-cookies-colombian-fare-bronx-nabe-article-1.2479580

**Comment by freejoe76** [comment]
The Subway Fare subnav is now gone, this issue is moot.
