### ISSUE TITLE
spacing issue with subway icons on splash page mobile 

### ISSUE THREAD

**Issue by ssmirti** [nydailynews/restaurant-guide#91]
The R line icon on the splash page are spaced too far down on mobile. 
![image uploaded from ios 2](https://user-images.githubusercontent.com/25779035/29416153-3fec70fa-8333-11e7-8728-bebca4da935a.jpg)

**Comment by freejoe76** [comment]
This is fixed. http://interactive.nydailynews.com/map/nyc-subway-restaurant-guide/splash.html
